name: Backend Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux, X64, udacity-devops-p4]
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
    - run: pwd
    - run: touch .env
    - run: npm install
    - run: npm run build
    - run: npm run tsbuild
